# default: --format pretty features
<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format progress features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "#{rerun_opts} --format rerun --out rerun.txt --strict --tags @wip --tags ~@disabled -r features" #  --tags ~@selenium "
%>
autotest: <%= std_opts %>
default: --format pretty --strict --tags ~@wip --tags ~@disabled -r features
wip: --tags @wip:4 --tags ~@disabled -r features --wip features
